type Priority = 'P0' | 'P1' | 'P2' | 'P3'
type FilterKey = 'All' | 'P0/P1' | 'Regulatory Impact' | 'Renewal Risk' | 'Modernization'

type Request = {
  customerType: string; requestSummary: string; businessDriver: string; renewalRisk: number; regulatoryImpact: number;
  engineeringEffort: number; modernizationValue: number; priority: Priority; pmDecision: string; whyItMatters: string;
  riskIfIgnored: string; suggestedResponse: string; notes: string; adoptionImpact: string
}

const requests: Request[] = [
  { customerType:'Regional Bank', requestSummary:'Maintain reporting workflow continuity for a regulatory filing process', businessDriver:'Regulatory reporting deadline', renewalRisk:5, regulatoryImpact:5, engineeringEffort:3, modernizationValue:2, priority:'P0', pmDecision:'Build / hot-track', whyItMatters:'Missed filing workflow risks compliance and account trust.', riskIfIgnored:'Potential filing delay and renewal concerns.', suggestedResponse:'Fast-track scoped fix and communicate milestone plan.', notes:'Coordinate reporting SME plus release manager.', adoptionImpact:'Protects retention and regulated workflow adoption.'},
  { customerType:'National Retailer', requestSummary:'Provide dependency visibility before modernizing legacy reporting jobs', businessDriver:'Migration planning', renewalRisk:4, regulatoryImpact:2, engineeringEffort:3, modernizationValue:5, priority:'P1', pmDecision:'Prioritize discovery', whyItMatters:'Dependency mapping reduces modernization surprises.', riskIfIgnored:'Migration delays and avoidable outages.', suggestedResponse:'Ship discovery output first, then phased improvements.', notes:'Architecture to define metadata export format.', adoptionImpact:'Improves confidence to adopt modernization tooling.'},
  { customerType:'Financial Institution', requestSummary:'Improve audit visibility for source library changes', businessDriver:'Audit readiness', renewalRisk:4, regulatoryImpact:5, engineeringEffort:2, modernizationValue:2, priority:'P1', pmDecision:'Add to roadmap', whyItMatters:'Audit traceability is critical for regulated operations.', riskIfIgnored:'Audit exceptions and escalations.', suggestedResponse:'Add immutable change-report view with export.', notes:'Product owner to align with audit personas.', adoptionImpact:'Strengthens retention via compliance confidence.'},
  { customerType:'Insurance Provider', requestSummary:'Create migration assessment output for legacy reporting assets', businessDriver:'Modernization planning', renewalRisk:3, regulatoryImpact:2, engineeringEffort:3, modernizationValue:5, priority:'P1', pmDecision:'Pilot with design partner', whyItMatters:'Assessment output supports low-risk migration planning.', riskIfIgnored:'Modernization stalls and shadow tooling.', suggestedResponse:'Pilot with one design partner and measure usage.', notes:'Define minimal viability metrics for pilot success.', adoptionImpact:'Encourages adoption with reduced disruption risk.'},
  { customerType:'Support Organization', requestSummary:'Reduce repeated upgrade planning confusion', businessDriver:'Support burden reduction', renewalRisk:2, regulatoryImpact:1, engineeringEffort:1, modernizationValue:1, priority:'P2', pmDecision:'Improve documentation and release notes', whyItMatters:'Recurring confusion consumes support capacity.', riskIfIgnored:'Higher ticket volume and slower upgrades.', suggestedResponse:'Standardize release planning checklist and comms.', notes:'Support lead to co-author upgrade runbook.', adoptionImpact:'Improves upgrade completion and customer satisfaction.'},
  { customerType:'Enterprise Bank', requestSummary:'AI-assisted documentation for legacy reporting jobs', businessDriver:'Knowledge preservation', renewalRisk:2, regulatoryImpact:2, engineeringEffort:4, modernizationValue:4, priority:'P2', pmDecision:'Explore controlled pilot', whyItMatters:'Institutional knowledge loss creates operational risk.', riskIfIgnored:'Longer onboarding and troubleshooting cycles.', suggestedResponse:'Run constrained pilot with human review controls.', notes:'Ensure generated content remains advisory only.', adoptionImpact:'May increase documentation adoption over time.'},
  { customerType:'Large Retail Chain', requestSummary:'Better release impact communication for scheduled upgrades', businessDriver:'Operational continuity', renewalRisk:4, regulatoryImpact:2, engineeringEffort:2, modernizationValue:2, priority:'P1', pmDecision:'Improve release readiness workflow', whyItMatters:'Proactive communication minimizes upgrade disruption.', riskIfIgnored:'Unexpected issues and trust erosion.', suggestedResponse:'Add release impact summary template plus timeline.', notes:'Coordinate PMM and support comms cadence.', adoptionImpact:'Improves confidence in ongoing platform updates.'},
  { customerType:'Financial Services Firm', requestSummary:'Compatibility support for existing batch/reporting workflows', businessDriver:'Business continuity', renewalRisk:5, regulatoryImpact:4, engineeringEffort:3, modernizationValue:3, priority:'P0', pmDecision:'Build / protect existing workflow', whyItMatters:'Compatibility is essential for mission-critical operations.', riskIfIgnored:'Workflow breakage and acute churn risk.', suggestedResponse:'Prioritize compatibility guardrails and validation tests.', notes:'Engineering lead to define regression suite coverage.', adoptionImpact:'Protects retention during platform evolution.'}
]

const backlogPreview = [
  ['Customer Request Intake', 'Define request intake schema', 'P0', 'Complete'],
  ['Triage Scoring Model', 'Publish scoring definitions', 'P0', 'Complete'],
  ['Prioritization Dashboard UI', 'Build overview cards and filters', 'P1', 'Complete'],
  ['Request Detail and PM Recommendation', 'Display decision rationale panel', 'P0', 'Complete'],
  ['Adoption and Retention View', 'Track high renewal-risk counts', 'P1', 'Complete'],
  ['Regulatory and Audit Impact View', 'Add regulatory-impact filter', 'P0', 'Complete']
]

import { useMemo, useState } from 'react'
export function App() {
  const [filter, setFilter] = useState<FilterKey>('All'); const [selected, setSelected] = useState<Request>(requests[0])
  const filtered = useMemo(() => requests.filter(r => filter==='All' ? true : filter==='P0/P1' ? ['P0','P1'].includes(r.priority) : filter==='Regulatory Impact' ? r.regulatoryImpact>=4 : filter==='Renewal Risk' ? r.renewalRisk>=4 : r.modernizationValue>=4), [filter])
  return <main className='container'><header><h1>Enterprise Mainframe Product Triage Dashboard</h1><p>Modernization without disruption for mature B2B software products</p></header>
  <section className='cards'>{[['Total Customer Requests', requests.length],['P0/P1 Priorities', requests.filter(r=>['P0','P1'].includes(r.priority)).length],['High Renewal Risk', requests.filter(r=>r.renewalRisk>=4).length],['Regulatory / Audit Impact', requests.filter(r=>r.regulatoryImpact>=4).length],['Modernization-Linked Requests', requests.filter(r=>r.modernizationValue>=4).length]].map(([l,v])=><div className='card' key={l as string}><h3>{l}</h3><div>{v}</div></div>)}</section>
  <section className='filters'>{(['All','P0/P1','Regulatory Impact','Renewal Risk','Modernization'] as FilterKey[]).map(f=><button key={f} className={f===filter?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</section>
  <section><table><thead><tr><th>Customer Type</th><th>Request Summary</th><th>Business Driver</th><th>Renewal Risk</th><th>Regulatory Impact</th><th>Engineering Effort</th><th>Modernization Value</th><th>Priority</th><th>PM Decision</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={i} onClick={()=>setSelected(r)}><td>{r.customerType}</td><td>{r.requestSummary}</td><td>{r.businessDriver}</td><td>{r.renewalRisk}</td><td>{r.regulatoryImpact}</td><td>{r.engineeringEffort}</td><td>{r.modernizationValue}</td><td>{r.priority}</td><td>{r.pmDecision}</td></tr>)}</tbody></table></section>
  <section className='detail'><h2>Request Detail</h2><p><strong>Request summary:</strong> {selected.requestSummary}</p><p><strong>Why it matters:</strong> {selected.whyItMatters}</p><p><strong>Risk if ignored:</strong> {selected.riskIfIgnored}</p><p><strong>Suggested PM response:</strong> {selected.suggestedResponse}</p><p><strong>Engineering/Product Owner notes:</strong> {selected.notes}</p><p><strong>Adoption or retention impact:</strong> {selected.adoptionImpact}</p></section>
  <section className='detail'><h2>Scoring Explanation</h2><p>Requests are scored 1–5 across renewal risk, regulatory impact, severity, revenue impact, effort, support burden reduction, modernization value, adoption potential, strategic fit, and customers affected. PMs use this input plus judgment to assign P0/P1/P2/P3.</p></section>
  <section><h2>Product Backlog Preview</h2><table><thead><tr><th>Epic</th><th>User Story</th><th>Priority</th><th>Status</th></tr></thead><tbody>{backlogPreview.map((r,i)=><tr key={i}><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td></tr>)}</tbody></table></section>
  <footer>This is a public portfolio prototype using fictional customer data. It does not contain proprietary information or represent any specific company’s internal roadmap.</footer>
  </main>
}
